server:
  port: 8008

cxf:
  contextPath: /personal-details

dao:
  mongo:
    serverAddresses:
      - host: localhost
        port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: personal-details
    personalDetails:
      name: personalDetailsV2
      username: personalDetailsV2User
      password: Passw0rd
  kafkaProducer:
    url: localhost:9092
    retries: 0
    topic: mongo-updates

migration:
  source:
    mongo:
      serverAddresses:
        - host: localhost
          port: 27017
      options:
        ssl:
          enabled: false
          invalidHostnameAllowed: false
      dbName: personal-details
      collection:
        name: personalDetails
        username: personalDetailsUser
        password: Passw0rd
    kafkaConsumer:
      url: localhost:9092
      retries: 0
      topic: mongo-updates
  # TODO: These properties may not be required - could the 'dao.xxx' properties be used??
  destination:
    mongo:
      serverAddresses:
        - host: localhost
          port: 27017
      options:
        ssl:
          enabled: false
          invalidHostnameAllowed: false
      dbName: personal-details
      collection:
        name: personalDetailsV2
        username: personalDetailsV2User
        password: Passw0rd
    kafkaProducer:
      url: localhost:9092
      retries: 0
      topic: mongo-migration-personal-details

---

spring:
  profiles: docker
dao:
  mongo:
    serverAddresses:
      - host: mongo-server
        port: 27017
  kafkaProducer:
    url: kafka-server:9092

migration:
  source:
    mongo:
      - host: mongo-server
        port: 27017
    kafkaConsumer:
      url: kafka-server:9092
  destination:
    mongo:
      - host: mongo-server
        port: 27017
    kafkaProducer:
      url: kafka-server:9092
