server:
  port: 9009

cxf:
  contextPath: /migration

source:
  mongo:
    serverAddresses:
      - host: localhost
        port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: personal-details
    collection:
      name: personalDetails
      username: personalDetailsUser
      password: Passw0rd

destination:
  mongo:
    serverAddresses:
      - host: localhost
        port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: personal-details
    collection:
      name: personalDetailsV2
      username: personalDetailsUser
      password: Passw0rd

kafka:
  url: localhost:9092
  retries: 0
  topic: mongo.updates